ALTER TABLE school 
ADD COLUMN description VARCHAR(255),
ADD COLUMN address VARCHAR(255),
ADD COLUMN city VARCHAR(100),
ADD COLUMN province VARCHAR(100),
ADD COLUMN postal_code VARCHAR(20),
ADD COLUMN phone VARCHAR(20),
ADD COLUMN email VARCHAR(100),
ADD COLUMN website VARCHAR(100),
ADD COLUMN logo VARCHAR(255),
ADD COLUMN banner VARCHAR(255),
ADD COLUMN established_year INT;